name: deploying Hexo project to GitHub pages
permissions:
  contents: write
on:
  push:
    branches:
      - main # main 分支有 push 行为时就触发这个 action
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12.22.12"

      - name: Install Pandoc
        run: |
          sudo apt-get install pandoc

      - name: Install and Build 🔧
        run: |
          npm install -g hexo-cli
          npm install
          hexo clean
          hexo generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          BASE_BRANCH: main
